# Generated by Django 6.0.4 on 2026-05-15 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='role',
            field=models.CharField(default='host', max_length=20),
        ),
        migrations.AlterField(
            model_name='host',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
