services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/django/Dockerfile
    container_name: gadigital-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - redis-cache
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend
    ports:
      - "5432:5432"

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"