# Generated by Django 6.0.4 on 2026-06-12 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mic_on', models.BooleanField(default=True)),
                ('video_on', models.BooleanField(default=True)),
                ('hand_raised', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.user')),
            ],
            options={
                'db_table': 'participant_states',
            },
        ),
    ]
