# Generated by Django 6.0.5 on 2026-05-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='participants',
            field=models.JSONField(default=list),
        ),
    ]
