# Generated by Django 6.0.6 on 2026-06-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKey',
        ),
    ]
