# Generated by Django 6.0.4 on 2026-05-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mic_on', models.BooleanField(default=True)),
                ('camera_on', models.BooleanField(default=True)),
            ],
        ),
    ]
