# Generated by Django 6.0.4 on 2026-05-25 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('meeting_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('is_recording_enabled', models.BooleanField(default=False)),
                ('is_waiting_room_enabled', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_created', to='users.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='users.product')),
            ],
            options={
                'db_table': 'meetings',
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('invitation_status', models.CharField(blank=True, max_length=50, null=True)),
                ('joined_once', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to='users.user')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', related_query_name='participation', to='users.user')),
            ],
            options={
                'db_table': 'meeting_participants',
            },
        ),
        migrations.CreateModel(
            name='MeetingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('peak_participant_count', models.IntegerField(default=0)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('recording_status', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='meetings.meeting')),
                ('started_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_started', to='users.user')),
            ],
            options={
                'db_table': 'meeting_sessions',
            },
        ),
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('reconnect_count', models.IntegerField(default=0)),
                ('speaking_duration_seconds', models.IntegerField(default=0)),
                ('screen_share_duration_seconds', models.IntegerField(default=0)),
                ('network_avg_latency', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('meeting_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_sessions', to='meetings.meetingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_sessions', to='users.user')),
            ],
            options={
                'db_table': 'participant_sessions',
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recording_type', models.CharField(blank=True, max_length=50, null=True)),
                ('storage_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='meetings.meetingsession')),
            ],
            options={
                'db_table': 'recordings',
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recurrence_type', models.CharField(max_length=50)),
                ('interval_value', models.IntegerField(blank=True, null=True)),
                ('weekdays', models.JSONField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='meetings.meeting')),
            ],
            options={
                'db_table': 'recurrence_rules',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('action_items', models.JSONField(blank=True, null=True)),
                ('generated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='meetings.meetingsession')),
                ('recording', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcripts', to='meetings.recording')),
            ],
            options={
                'db_table': 'transcripts',
            },
        ),
    ]
