# Generated by Django 6.0.5 on 2026-05-26 08:11

import apps.meetings.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_code',
            field=models.CharField(default=apps.meetings.utils.generate_meeting_code, max_length=100, unique=True),
        ),
    ]
