# Generated by Django 6.0.4 on 2026-05-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_recordingstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_link', models.URLField()),
                ('recording_type', models.CharField(default='VIDEO', max_length=20)),
                ('storage_provider', models.CharField(default='LOCAL', max_length=20)),
                ('processing_status', models.CharField(default='STARTED', max_length=20)),
                ('started_by', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='RecordingState',
        ),
    ]
