# Generated by Django 6.0.4 on 2026-05-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_recording_delete_recordingstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantstate',
            old_name='camera_on',
            new_name='video_on',
        ),
        migrations.AddField(
            model_name='participantstate',
            name='hand_raised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
             model_name='participantstate',
             name='meeting_id',
            field=models.CharField(
                 max_length=100,
                default='meeting_001'
             ),
        ),
        migrations.AddField(
            model_name='participantstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='participantstate',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
