# Generated by Django 6.0.5 on 2026-06-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_rename_camera_on_participantstate_video_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantstate',
            name='meeting_id',
            field=models.CharField(max_length=100),
        ),
    ]
